<a href="https://colab.research.google.com/github/sushama1306/DecisionTree-classification/blob/main/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df = pd.read_csv('/content/gender_submission.csv')

df.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [ ]:
from google.colab import files



uploaded = files.upload()

Saving gender_submission.csv to gender_submission (2).csv

In [ ]:
import pandas as pd

df = pd.read_csv(list(uploaded.keys())[0])

df.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [ ]:
print(df.head())
print(df.shape)

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1
(418, 2)

In [ ]:
X = df[['PassengerId']]
y = df['Survived']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = DecisionTreeClassifier(random_state=42)

In [ ]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5238095238095238

In [ ]:
print("classification report",classification_report(y_test,y_pred))

classification report               precision    recall  f1-score   support

           0       0.59      0.64      0.62        50
           1       0.40      0.35      0.38        34

    accuracy                           0.52        84
   macro avg       0.50      0.50      0.50        84
weighted avg       0.51      0.52      0.52        84

In [ ]:
print("confusion matrix",confusion_matrix( y_test,y_pred))

confusion matrix [[32 18]
 [22 12]]

In [ ]:
a = int(input("Enter PassengerId: "))

a = np.array([[a]])

prediction = model.predict(a)

print("Prediction:", prediction)

if int(prediction[0]) == 1:
    print("Passenger Survived")
else:
    print("Passenger Not Survived")

Enter PassengerId: 899
Prediction: [0]
Passenger Not Survived

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(